### ISSUE TITLE
Crashes whilst autosaving when building

### ISSUE THREAD

**Issue by ghost** [arawkins/atom-monkey#4]
Using the latest plugin and latest Atom (1.16.0) on MacOs when I go to build with the "Auto save before building option" turned on, an exception is thrown.

[Enter steps to reproduce:]

1. Load up a monkey file
2. Have "Save files on build" turned on
3. Build

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [language-monkey2](https://github.com/arawkins/atom-monkey) package 1.4.2

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:15)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1058:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:920:26)
    at Object.build (/packages/language-monkey2/lib/monkey.coffee:191:28)
    at Object.buildCurrent (/packages/language-monkey2/lib/monkey.coffee:171:14)
    at /packages/language-monkey2/lib/monkey.coffee:53:18)
    at HTMLButtonElement.dispatch (/packages/language-monkey2/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLButtonElement.elemData.handle (/packages/language-monkey2/node_modules/jquery/dist/jquery.js:4549:28)
```

### Commands

```
     -9:40.4.0 core:save (input.hidden-input)
     -9:09.0 monkey2:buildCurrent (input.hidden-input)
     -9:01.0 core:backspace (input.hidden-input)
     -8:58.2.0 settings-view:open (input.hidden-input)
     -8:58.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:56.1.0 settings-view:open (div.package-detail.panels-item)
  2x -8:16.4.0 core:backspace (input.hidden-input)
     -7:49.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:39.9.0 autocomplete-clang:go-declaration (span.syntax--storage.syntax--type.syntax--monkey2)
     -5:53.4.0 core:save (input.hidden-input)
     -1:23.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:16.3.0 settings-view:open (input.hidden-input)
  4x -1:16.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-toolbar 0.1.6 
autocomplete-clang 0.9.4 
dartlang 0.6.28 
go-plus 3.5.2 
gpp-compiler 3.0.6 
language-monkey2 1.4.2 
linter 1.11.14 
linter-clang 3.4.4 
linter-gcc 0.6.15 
script 3.7.3 
synced-sidebar 0.4.3 
```

**Comment by arawkins** [comment]
Hey, thanks for filing the issue. I've published v1.4.3 with a fix. File paths are now verified before attempting to save. For now, if a file hasn't been saved yet (ie. it doesn't have a defined path on your), it gets skipped by the auto-save.
